---
dist: xenial
language: python
python: 3.7
services: docker
env:
  global:
    - IMAGE_NAME=dhsncats/gophish
    - DOCKER_USER=felddy
    - secure: >-
        3gPdChpfNf3aDj1qX3Xr1jMnqWfE1ncnc/txCDLNX4fJLv4H+9CU04qs8ncWNKwofkO
        s4vHYei7uRG9Dv1/yXZPLpBWXRFFyGt+kIc5E5lxaRHukh0NtC3ZINf/MR+QmUBYYxo
        c+CMPAdJ9pLNTZ2rYA93M2EDqiGStt+0Z28roSbwEga3Lj7rGISIPeX4tsozvxW75tt
        5b5MDD63SwMJAPZ81zfXPAwYbXkO7PXn9UJTLOohFL7oIUovJzI41Acuhi/TGkrlvVi
        yDSRQdOYG2dwxLcgds+zJ+/0zoqxgtG7v4FcVtTHJLBoTPV864naCAI50I7YHt09wnP
        qH6SppXzZYFIFvzs+JoPAqHbBVyk0tjzxWn8Zp7aH/gihXY+h5+bI0cZafR4Am8CVS3
        mJrF5mEUdkeNOQU76GzoI8wbuRVQp+JFKG9JOWPUrFRoxuIRFWUewLF3I33o0znsRK2
        x3jkECnEPImt3YiCYcV9k+z/JADXVvVuS7OqGQciL8w/Pn+8hkKvB2NYPuhs05L4BLb
        iKyMnGteqjRcEnC+yQsxZ0oX1Nc4ZnVetKuoQIQgylnLVyF60kjgoJeLzOTAyVtIISz
        8MEmR096TvBPf76dKB+w2As8zViE68qvHWaz857fKRuks6APgOpbhY0F5B/T5lrs8cM
        SWpXBFLYoNQ7I=
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
install:
  - pip install --upgrade -r requirements-test.txt
  - docker build -t "$IMAGE_NAME" .
before_script:
  - docker-compose up -d
script:
  - pre-commit run --all-files
  - pytest -v
after_script:
  - docker-compose down
before_deploy:
  - version=$(./bump_version.sh show)
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PW"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:latest" &&
      docker push "${IMAGE_NAME}:${version}"
    on:
      tags: false
      python: '3.7'
