---
dist: xenial
language: python
python: 3.7
services: docker
env:
  global:
    - IMAGE_NAME=dhsncats/gophish
    - DOCKER_USER=felddy
    - secure: >-
        RIsRzjnudSzxWX/jhkjc+b8IsczvPPW5/Tn1m3ySsZzyjhKEr5qI/Jz/5S97IXlCR/x
        aqqMOkPCA9w9Tr3SLqHpuL4VcWxol8WRjvNIkPyOt760cN5jiz2RNvpVLo1ILBR2ZKx
        RI+y/YUXEIkAmRkIukpoX6qe5ERFyrmr8VhDzdCANPrPxLf4Unfq5ioww1x+nyal5IM
        ARPjE6LFUClbgC/0SB/4LZksmk38BNpea/nPPGPCkGx14MiZqtwIxC7dCieR2XvxtwN
        nzqbru3HYUuXIxv1llH60RJsoofOMAjiRsySNmmPAJt9Eu+T2H85zcIV6xyyeZ6kuOt
        6LbY2W/FRqJl58IGljaf+1Ovm7L5XEtiYeOTO2Eg1rAPoi6+C75eGNo3NriF4cmZaBL
        hAno1fZogJ/g9piW5Hc33jjlBLStJebJF21DK4kTB1yFMOooVk7kBsB2MHkGHJrULkF
        dR1NRJAaqwSLL/i3nl8V9SzGz+n0xhi7eDbo3bo7nD4Bm5S7UoiNljLth32G7NAcohW
        Pf/vMGPSaxV6Z6T5oQAem6os7Sl5wORjTwiRfWyq96yWmvno+SXqKfYKEaktSe1gJ/1
        qGdKl4UmQZOoyOcqOCqBJOzETvspboVG0SEp83h3iTB2kSq6GZ9YOCe1F4ZVg6mqer/
        55RC8BypojkU8=
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
install:
  - pip install --upgrade -r requirements-test.txt
  - travis_scripts/build_docker_image.sh
before_script:
  - docker-compose up -d
script:
  - pre-commit run --all-files
  - pytest -v
after_script:
  - docker-compose down
deploy:
  - provider: script
    script: bash travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.7'
