---
dist: xenial
language: python
python: 3.7
services: docker
env:
  global:
    - IMAGE_NAME=dhsncats/gophish
    - DOCKER_USER=felddy
    - secure: >-
        i8NeyOw/IpSIA3dRBSiqNKRBUMC9YuYzSuM4wwvAOXCt6rJMzJxMSNzdu7R7oE6I11P
        XNQfJKQI5A/nDIt4LVSb3mz1AC/imClkCCp/HCwBuXOo9VGx7ckhpDRpWvSZUjVLRNP
        krU12ODGHTk9pvilCGCqdh08fWEEODXIFxNhC9uGmk463bNAqKmujMW6saMhAPHv4/J
        1GgTF26SdiK65OvhNPaNJUfhIN6tMbvQG/bRAdVaWSsQJVWKEUjFvcNikQD6FVRW/8A
        //OOTqW+3Tkd8EiEVU3Hb34ZrwVJx1Y3rMivr2otHRLUNeGJeGVDb6yErSEu/x+1r6Z
        kqFBCr2kS9xvsJ79BVteg3GFZtjo5vGbOf/W9j+eeZEEIJXqyGOOE3bU3VWPSMeEYsj
        nLh3t3uI4qkq7Wi/eoYLT55/NAV6+bMD6GToo7iNJVTvM5M35C9+sp05LAfP7I/uPbX
        DafVD2Ha8a82sVAChrXVGMm/k0gqlW9pxu7U+v16yFEgF2alrCOL9Pp089HsIRa41W7
        mtWUOLPU2dP+ZeqU/RP8mEyEp+LxMjL9gMlOr9TJWCgKROYMnCKOvXnejnC51qbCUl+
        As9Pa35XD8hs22D048vEAy9q1h8vCTL1dFCi7wm7sEGY7C+2/DE275vLGH/ydXC1JlS
        QOrH3aqcbf67I=
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
install:
  - pip install --upgrade -r requirements-test.txt
  - travis_scripts/build_docker_image.sh
before_script:
  - docker-compose up -d
script:
  - pre-commit run --all-files
  - pytest -v
after_script:
  - docker-compose down
deploy:
  - provider: script
    script: bash travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.7'
